// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Tx struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
	Hash                 string   `protobuf:"bytes,5,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Signature            string   `protobuf:"bytes,6,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Time                 int64    `protobuf:"varint,7,opt,name=Time,proto3" json:"Time,omitempty"`
	Script               string   `protobuf:"bytes,8,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Tx) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Tx) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Tx) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Tx) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Tx) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Tx) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Tx) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

type ResTx struct {
	Txs                  []*Tx    `protobuf:"bytes,1,rep,name=Txs,proto3" json:"Txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResTx) Reset()         { *m = ResTx{} }
func (m *ResTx) String() string { return proto.CompactTextString(m) }
func (*ResTx) ProtoMessage()    {}
func (*ResTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *ResTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResTx.Unmarshal(m, b)
}
func (m *ResTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResTx.Marshal(b, m, deterministic)
}
func (m *ResTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResTx.Merge(m, src)
}
func (m *ResTx) XXX_Size() int {
	return xxx_messageInfo_ResTx.Size(m)
}
func (m *ResTx) XXX_DiscardUnknown() {
	xxx_messageInfo_ResTx.DiscardUnknown(m)
}

var xxx_messageInfo_ResTx proto.InternalMessageInfo

func (m *ResTx) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type ReqTx struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTx) Reset()         { *m = ReqTx{} }
func (m *ReqTx) String() string { return proto.CompactTextString(m) }
func (*ReqTx) ProtoMessage()    {}
func (*ReqTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *ReqTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTx.Unmarshal(m, b)
}
func (m *ReqTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTx.Marshal(b, m, deterministic)
}
func (m *ReqTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTx.Merge(m, src)
}
func (m *ReqTx) XXX_Size() int {
	return xxx_messageInfo_ReqTx.Size(m)
}
func (m *ReqTx) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTx.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTx proto.InternalMessageInfo

func (m *ReqTx) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ReqTxByHash struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTxByHash) Reset()         { *m = ReqTxByHash{} }
func (m *ReqTxByHash) String() string { return proto.CompactTextString(m) }
func (*ReqTxByHash) ProtoMessage()    {}
func (*ReqTxByHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *ReqTxByHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTxByHash.Unmarshal(m, b)
}
func (m *ReqTxByHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTxByHash.Marshal(b, m, deterministic)
}
func (m *ReqTxByHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTxByHash.Merge(m, src)
}
func (m *ReqTxByHash) XXX_Size() int {
	return xxx_messageInfo_ReqTxByHash.Size(m)
}
func (m *ReqTxByHash) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTxByHash.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTxByHash proto.InternalMessageInfo

func (m *ReqTxByHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ReqBalance struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBalance) Reset()         { *m = ReqBalance{} }
func (m *ReqBalance) String() string { return proto.CompactTextString(m) }
func (*ReqBalance) ProtoMessage()    {}
func (*ReqBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *ReqBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBalance.Unmarshal(m, b)
}
func (m *ReqBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBalance.Marshal(b, m, deterministic)
}
func (m *ReqBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBalance.Merge(m, src)
}
func (m *ReqBalance) XXX_Size() int {
	return xxx_messageInfo_ReqBalance.Size(m)
}
func (m *ReqBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBalance proto.InternalMessageInfo

func (m *ReqBalance) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ResBalance struct {
	Balnce               uint64   `protobuf:"varint,1,opt,name=balnce,proto3" json:"balnce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResBalance) Reset()         { *m = ResBalance{} }
func (m *ResBalance) String() string { return proto.CompactTextString(m) }
func (*ResBalance) ProtoMessage()    {}
func (*ResBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *ResBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResBalance.Unmarshal(m, b)
}
func (m *ResBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResBalance.Marshal(b, m, deterministic)
}
func (m *ResBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResBalance.Merge(m, src)
}
func (m *ResBalance) XXX_Size() int {
	return xxx_messageInfo_ResBalance.Size(m)
}
func (m *ResBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_ResBalance.DiscardUnknown(m)
}

var xxx_messageInfo_ResBalance proto.InternalMessageInfo

func (m *ResBalance) GetBalnce() uint64 {
	if m != nil {
		return m.Balnce
	}
	return 0
}

type ReqBlockByNumber struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBlockByNumber) Reset()         { *m = ReqBlockByNumber{} }
func (m *ReqBlockByNumber) String() string { return proto.CompactTextString(m) }
func (*ReqBlockByNumber) ProtoMessage()    {}
func (*ReqBlockByNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *ReqBlockByNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBlockByNumber.Unmarshal(m, b)
}
func (m *ReqBlockByNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBlockByNumber.Marshal(b, m, deterministic)
}
func (m *ReqBlockByNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBlockByNumber.Merge(m, src)
}
func (m *ReqBlockByNumber) XXX_Size() int {
	return xxx_messageInfo_ReqBlockByNumber.Size(m)
}
func (m *ReqBlockByNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBlockByNumber.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBlockByNumber proto.InternalMessageInfo

func (m *ReqBlockByNumber) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ReqBlockByHash struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBlockByHash) Reset()         { *m = ReqBlockByHash{} }
func (m *ReqBlockByHash) String() string { return proto.CompactTextString(m) }
func (*ReqBlockByHash) ProtoMessage()    {}
func (*ReqBlockByHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *ReqBlockByHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBlockByHash.Unmarshal(m, b)
}
func (m *ReqBlockByHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBlockByHash.Marshal(b, m, deterministic)
}
func (m *ReqBlockByHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBlockByHash.Merge(m, src)
}
func (m *ReqBlockByHash) XXX_Size() int {
	return xxx_messageInfo_ReqBlockByHash.Size(m)
}
func (m *ReqBlockByHash) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBlockByHash.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBlockByHash proto.InternalMessageInfo

func (m *ReqBlockByHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type RespBlock struct {
	Height               uint64   `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	PrevBlockHash        string   `protobuf:"bytes,2,opt,name=PrevBlockHash,proto3" json:"PrevBlockHash,omitempty"`
	Txs                  []*Tx    `protobuf:"bytes,3,rep,name=Txs,proto3" json:"Txs,omitempty"`
	Root                 string   `protobuf:"bytes,4,opt,name=Root,proto3" json:"Root,omitempty"`
	Version              uint64   `protobuf:"varint,5,opt,name=Version,proto3" json:"Version,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Hash                 string   `protobuf:"bytes,7,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Miner                string   `protobuf:"bytes,8,opt,name=Miner,proto3" json:"Miner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespBlock) Reset()         { *m = RespBlock{} }
func (m *RespBlock) String() string { return proto.CompactTextString(m) }
func (*RespBlock) ProtoMessage()    {}
func (*RespBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *RespBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespBlock.Unmarshal(m, b)
}
func (m *RespBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespBlock.Marshal(b, m, deterministic)
}
func (m *RespBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespBlock.Merge(m, src)
}
func (m *RespBlock) XXX_Size() int {
	return xxx_messageInfo_RespBlock.Size(m)
}
func (m *RespBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_RespBlock.DiscardUnknown(m)
}

var xxx_messageInfo_RespBlock proto.InternalMessageInfo

func (m *RespBlock) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *RespBlock) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *RespBlock) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

func (m *RespBlock) GetRoot() string {
	if m != nil {
		return m.Root
	}
	return ""
}

func (m *RespBlock) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RespBlock) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RespBlock) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *RespBlock) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

type ResposeTxs struct {
	Txs                  []*Tx    `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResposeTxs) Reset()         { *m = ResposeTxs{} }
func (m *ResposeTxs) String() string { return proto.CompactTextString(m) }
func (*ResposeTxs) ProtoMessage()    {}
func (*ResposeTxs) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *ResposeTxs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResposeTxs.Unmarshal(m, b)
}
func (m *ResposeTxs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResposeTxs.Marshal(b, m, deterministic)
}
func (m *ResposeTxs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResposeTxs.Merge(m, src)
}
func (m *ResposeTxs) XXX_Size() int {
	return xxx_messageInfo_ResposeTxs.Size(m)
}
func (m *ResposeTxs) XXX_DiscardUnknown() {
	xxx_messageInfo_ResposeTxs.DiscardUnknown(m)
}

var xxx_messageInfo_ResposeTxs proto.InternalMessageInfo

func (m *ResposeTxs) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type ResposeNonce struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResposeNonce) Reset()         { *m = ResposeNonce{} }
func (m *ResposeNonce) String() string { return proto.CompactTextString(m) }
func (*ResposeNonce) ProtoMessage()    {}
func (*ResposeNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *ResposeNonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResposeNonce.Unmarshal(m, b)
}
func (m *ResposeNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResposeNonce.Marshal(b, m, deterministic)
}
func (m *ResposeNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResposeNonce.Merge(m, src)
}
func (m *ResposeNonce) XXX_Size() int {
	return xxx_messageInfo_ResposeNonce.Size(m)
}
func (m *ResposeNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_ResposeNonce.DiscardUnknown(m)
}

var xxx_messageInfo_ResposeNonce proto.InternalMessageInfo

func (m *ResposeNonce) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type ReqNonce struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqNonce) Reset()         { *m = ReqNonce{} }
func (m *ReqNonce) String() string { return proto.CompactTextString(m) }
func (*ReqNonce) ProtoMessage()    {}
func (*ReqNonce) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *ReqNonce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqNonce.Unmarshal(m, b)
}
func (m *ReqNonce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqNonce.Marshal(b, m, deterministic)
}
func (m *ReqNonce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqNonce.Merge(m, src)
}
func (m *ReqNonce) XXX_Size() int {
	return xxx_messageInfo_ReqNonce.Size(m)
}
func (m *ReqNonce) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqNonce.DiscardUnknown(m)
}

var xxx_messageInfo_ReqNonce proto.InternalMessageInfo

func (m *ReqNonce) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ReqTransaction struct {
	From                 string   `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Nonce                uint64   `protobuf:"varint,4,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Priv                 string   `protobuf:"bytes,5,opt,name=Priv,proto3" json:"Priv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTransaction) Reset()         { *m = ReqTransaction{} }
func (m *ReqTransaction) String() string { return proto.CompactTextString(m) }
func (*ReqTransaction) ProtoMessage()    {}
func (*ReqTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *ReqTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTransaction.Unmarshal(m, b)
}
func (m *ReqTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTransaction.Marshal(b, m, deterministic)
}
func (m *ReqTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTransaction.Merge(m, src)
}
func (m *ReqTransaction) XXX_Size() int {
	return xxx_messageInfo_ReqTransaction.Size(m)
}
func (m *ReqTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTransaction proto.InternalMessageInfo

func (m *ReqTransaction) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ReqTransaction) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *ReqTransaction) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReqTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *ReqTransaction) GetPriv() string {
	if m != nil {
		return m.Priv
	}
	return ""
}

type ResTransaction struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResTransaction) Reset()         { *m = ResTransaction{} }
func (m *ResTransaction) String() string { return proto.CompactTextString(m) }
func (*ResTransaction) ProtoMessage()    {}
func (*ResTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *ResTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResTransaction.Unmarshal(m, b)
}
func (m *ResTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResTransaction.Marshal(b, m, deterministic)
}
func (m *ResTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResTransaction.Merge(m, src)
}
func (m *ResTransaction) XXX_Size() int {
	return xxx_messageInfo_ResTransaction.Size(m)
}
func (m *ResTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ResTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ResTransaction proto.InternalMessageInfo

func (m *ResTransaction) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ReqCreateAddr struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateAddr) Reset()         { *m = ReqCreateAddr{} }
func (m *ReqCreateAddr) String() string { return proto.CompactTextString(m) }
func (*ReqCreateAddr) ProtoMessage()    {}
func (*ReqCreateAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *ReqCreateAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateAddr.Unmarshal(m, b)
}
func (m *ReqCreateAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateAddr.Marshal(b, m, deterministic)
}
func (m *ReqCreateAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateAddr.Merge(m, src)
}
func (m *ReqCreateAddr) XXX_Size() int {
	return xxx_messageInfo_ReqCreateAddr.Size(m)
}
func (m *ReqCreateAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateAddr.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateAddr proto.InternalMessageInfo

type RespCreateAddr struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Privkey              string   `protobuf:"bytes,2,opt,name=privkey,proto3" json:"privkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespCreateAddr) Reset()         { *m = RespCreateAddr{} }
func (m *RespCreateAddr) String() string { return proto.CompactTextString(m) }
func (*RespCreateAddr) ProtoMessage()    {}
func (*RespCreateAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{15}
}

func (m *RespCreateAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespCreateAddr.Unmarshal(m, b)
}
func (m *RespCreateAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespCreateAddr.Marshal(b, m, deterministic)
}
func (m *RespCreateAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespCreateAddr.Merge(m, src)
}
func (m *RespCreateAddr) XXX_Size() int {
	return xxx_messageInfo_RespCreateAddr.Size(m)
}
func (m *RespCreateAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_RespCreateAddr.DiscardUnknown(m)
}

var xxx_messageInfo_RespCreateAddr proto.InternalMessageInfo

func (m *RespCreateAddr) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RespCreateAddr) GetPrivkey() string {
	if m != nil {
		return m.Privkey
	}
	return ""
}

type ReqMaxBlockNumber struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMaxBlockNumber) Reset()         { *m = ReqMaxBlockNumber{} }
func (m *ReqMaxBlockNumber) String() string { return proto.CompactTextString(m) }
func (*ReqMaxBlockNumber) ProtoMessage()    {}
func (*ReqMaxBlockNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{16}
}

func (m *ReqMaxBlockNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMaxBlockNumber.Unmarshal(m, b)
}
func (m *ReqMaxBlockNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMaxBlockNumber.Marshal(b, m, deterministic)
}
func (m *ReqMaxBlockNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMaxBlockNumber.Merge(m, src)
}
func (m *ReqMaxBlockNumber) XXX_Size() int {
	return xxx_messageInfo_ReqMaxBlockNumber.Size(m)
}
func (m *ReqMaxBlockNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMaxBlockNumber.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMaxBlockNumber proto.InternalMessageInfo

type RespMaxBlockNumber struct {
	MaxNumber            uint64   `protobuf:"varint,1,opt,name=maxNumber,proto3" json:"maxNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespMaxBlockNumber) Reset()         { *m = RespMaxBlockNumber{} }
func (m *RespMaxBlockNumber) String() string { return proto.CompactTextString(m) }
func (*RespMaxBlockNumber) ProtoMessage()    {}
func (*RespMaxBlockNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{17}
}

func (m *RespMaxBlockNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespMaxBlockNumber.Unmarshal(m, b)
}
func (m *RespMaxBlockNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespMaxBlockNumber.Marshal(b, m, deterministic)
}
func (m *RespMaxBlockNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespMaxBlockNumber.Merge(m, src)
}
func (m *RespMaxBlockNumber) XXX_Size() int {
	return xxx_messageInfo_RespMaxBlockNumber.Size(m)
}
func (m *RespMaxBlockNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_RespMaxBlockNumber.DiscardUnknown(m)
}

var xxx_messageInfo_RespMaxBlockNumber proto.InternalMessageInfo

func (m *RespMaxBlockNumber) GetMaxNumber() uint64 {
	if m != nil {
		return m.MaxNumber
	}
	return 0
}

type ReqAddrByPriv struct {
	Priv                 string   `protobuf:"bytes,1,opt,name=priv,proto3" json:"priv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAddrByPriv) Reset()         { *m = ReqAddrByPriv{} }
func (m *ReqAddrByPriv) String() string { return proto.CompactTextString(m) }
func (*ReqAddrByPriv) ProtoMessage()    {}
func (*ReqAddrByPriv) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{18}
}

func (m *ReqAddrByPriv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAddrByPriv.Unmarshal(m, b)
}
func (m *ReqAddrByPriv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAddrByPriv.Marshal(b, m, deterministic)
}
func (m *ReqAddrByPriv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAddrByPriv.Merge(m, src)
}
func (m *ReqAddrByPriv) XXX_Size() int {
	return xxx_messageInfo_ReqAddrByPriv.Size(m)
}
func (m *ReqAddrByPriv) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAddrByPriv.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAddrByPriv proto.InternalMessageInfo

func (m *ReqAddrByPriv) GetPriv() string {
	if m != nil {
		return m.Priv
	}
	return ""
}

type RespAddrByPriv struct {
	Addr                 string   `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespAddrByPriv) Reset()         { *m = RespAddrByPriv{} }
func (m *RespAddrByPriv) String() string { return proto.CompactTextString(m) }
func (*RespAddrByPriv) ProtoMessage()    {}
func (*RespAddrByPriv) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{19}
}

func (m *RespAddrByPriv) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespAddrByPriv.Unmarshal(m, b)
}
func (m *RespAddrByPriv) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespAddrByPriv.Marshal(b, m, deterministic)
}
func (m *RespAddrByPriv) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespAddrByPriv.Merge(m, src)
}
func (m *RespAddrByPriv) XXX_Size() int {
	return xxx_messageInfo_RespAddrByPriv.Size(m)
}
func (m *RespAddrByPriv) XXX_DiscardUnknown() {
	xxx_messageInfo_RespAddrByPriv.DiscardUnknown(m)
}

var xxx_messageInfo_RespAddrByPriv proto.InternalMessageInfo

func (m *RespAddrByPriv) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

func init() {
	proto.RegisterType((*Tx)(nil), "message.Tx")
	proto.RegisterType((*ResTx)(nil), "message.res_tx")
	proto.RegisterType((*ReqTx)(nil), "message.req_tx")
	proto.RegisterType((*ReqTxByHash)(nil), "message.req_tx_by_hash")
	proto.RegisterType((*ReqBalance)(nil), "message.req_balance")
	proto.RegisterType((*ResBalance)(nil), "message.res_balance")
	proto.RegisterType((*ReqBlockByNumber)(nil), "message.req_block_by_number")
	proto.RegisterType((*ReqBlockByHash)(nil), "message.req_block_by_hash")
	proto.RegisterType((*RespBlock)(nil), "message.resp_block")
	proto.RegisterType((*ResposeTxs)(nil), "message.respose_txs")
	proto.RegisterType((*ResposeNonce)(nil), "message.respose_nonce")
	proto.RegisterType((*ReqNonce)(nil), "message.req_nonce")
	proto.RegisterType((*ReqTransaction)(nil), "message.req_transaction")
	proto.RegisterType((*ResTransaction)(nil), "message.res_transaction")
	proto.RegisterType((*ReqCreateAddr)(nil), "message.req_create_addr")
	proto.RegisterType((*RespCreateAddr)(nil), "message.resp_create_addr")
	proto.RegisterType((*ReqMaxBlockNumber)(nil), "message.req_max_block_number")
	proto.RegisterType((*RespMaxBlockNumber)(nil), "message.resp_max_block_number")
	proto.RegisterType((*ReqAddrByPriv)(nil), "message.req_addr_by_priv")
	proto.RegisterType((*RespAddrByPriv)(nil), "message.resp_addr_by_priv")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 792 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x55, 0x4d, 0x6f, 0xf2, 0x46,
	0x10, 0xb6, 0xf9, 0x2c, 0x43, 0x49, 0x9a, 0x7d, 0x29, 0xf5, 0x6b, 0x25, 0x15, 0x5a, 0x25, 0x0d,
	0x87, 0x36, 0x87, 0x54, 0x51, 0xa5, 0xde, 0x20, 0x55, 0xe0, 0x92, 0x28, 0x72, 0xac, 0x5e, 0x91,
	0x21, 0xab, 0x60, 0x25, 0xb6, 0xc9, 0xee, 0x92, 0x9a, 0x9f, 0x55, 0xa9, 0xff, 0xa7, 0x7f, 0xe5,
	0xd5, 0x8c, 0x6d, 0xf0, 0x42, 0x38, 0x31, 0x33, 0xfb, 0xec, 0xb3, 0xf3, 0xf1, 0x8c, 0x81, 0x4e,
	0x24, 0x94, 0x0a, 0x5e, 0xc4, 0xd5, 0x52, 0x26, 0x3a, 0x61, 0xcd, 0xdc, 0xe5, 0xff, 0xd9, 0x50,
	0xf1, 0x53, 0xd6, 0x85, 0xfa, 0x43, 0x12, 0xcf, 0x85, 0x63, 0xf7, 0xed, 0x41, 0xcd, 0xcb, 0x1c,
	0xd6, 0x83, 0xc6, 0x30, 0x4a, 0x56, 0xb1, 0x76, 0x2a, 0x14, 0xce, 0x3d, 0xc6, 0xa0, 0x76, 0x27,
	0x93, 0xc8, 0xa9, 0xf6, 0xed, 0x41, 0xcb, 0x23, 0x9b, 0x1d, 0x41, 0xc5, 0x4f, 0x9c, 0x1a, 0x45,
	0x2a, 0x7e, 0x82, 0x98, 0x49, 0xa0, 0x16, 0x4e, 0x3d, 0xc3, 0xa0, 0xcd, 0x4e, 0xa1, 0xf5, 0x14,
	0xbe, 0xc4, 0x81, 0x5e, 0x49, 0xe1, 0x34, 0xe8, 0x60, 0x1b, 0xc0, 0x1b, 0x7e, 0x18, 0x09, 0xa7,
	0xd9, 0xb7, 0x07, 0x55, 0x8f, 0x6c, 0xcc, 0x40, 0xcd, 0x65, 0xb8, 0xd4, 0xce, 0x77, 0x04, 0xcf,
	0x3d, 0x7e, 0x09, 0x0d, 0x29, 0xd4, 0x54, 0xa7, 0xec, 0x0c, 0xaa, 0x7e, 0xaa, 0x1c, 0xbb, 0x5f,
	0x1d, 0xb4, 0xaf, 0xdb, 0x57, 0x45, 0x99, 0x7e, 0xea, 0x61, 0x9c, 0x73, 0x04, 0xbe, 0x23, 0xd0,
	0x81, 0x66, 0xf0, 0xfc, 0x2c, 0x85, 0x52, 0x54, 0x64, 0xcb, 0x2b, 0x5c, 0x7e, 0x0e, 0x47, 0x19,
	0x66, 0x3a, 0x5b, 0x4f, 0x17, 0x98, 0x28, 0x83, 0x1a, 0xfe, 0xe6, 0x40, 0xb2, 0xf9, 0x25, 0xb4,
	0x11, 0x35, 0x0b, 0xde, 0x02, 0xec, 0xcd, 0x61, 0xba, 0x0b, 0x04, 0xaa, 0x0d, 0xb0, 0x07, 0x8d,
	0x59, 0xf0, 0xb6, 0xed, 0x6d, 0xee, 0xf1, 0xdf, 0xe0, 0x0b, 0xf1, 0xbd, 0x25, 0xf3, 0x57, 0x7c,
	0x38, 0x5e, 0x45, 0x33, 0x21, 0x11, 0xbe, 0x10, 0xe1, 0xcb, 0x42, 0x17, 0xf0, 0xcc, 0xe3, 0x97,
	0x70, 0x62, 0xc0, 0x0f, 0xe6, 0xf9, 0xbf, 0x0d, 0x20, 0x85, 0x5a, 0x66, 0x50, 0xe4, 0x9b, 0x18,
	0x7c, 0x99, 0xc7, 0xce, 0xa1, 0xf3, 0x28, 0xc5, 0xc7, 0x08, 0x41, 0x34, 0xa8, 0x0a, 0x71, 0x98,
	0xc1, 0xa2, 0xbb, 0xd5, 0xcf, 0xbb, 0x8b, 0xef, 0x7b, 0x49, 0xa2, 0xf3, 0xb1, 0x93, 0x8d, 0x8d,
	0xf9, 0x5b, 0x48, 0x15, 0x26, 0x31, 0xcd, 0xbe, 0xe6, 0x15, 0x2e, 0x8e, 0x1f, 0x87, 0xaa, 0x74,
	0x10, 0x2d, 0x69, 0xfc, 0x55, 0x6f, 0x1b, 0xd8, 0x08, 0xa6, 0x59, 0x12, 0x4c, 0x17, 0xea, 0xf7,
	0x61, 0x2c, 0x64, 0x3e, 0xfd, 0xcc, 0xe1, 0xbf, 0x52, 0x83, 0x97, 0x89, 0x12, 0x53, 0x9d, 0x2a,
	0xcc, 0x51, 0x1f, 0x50, 0x80, 0x4e, 0x71, 0x1c, 0x9d, 0x02, 0x1d, 0x93, 0xaa, 0xbb, 0x50, 0x8f,
	0xcb, 0x5a, 0x27, 0x87, 0x5f, 0x40, 0x0b, 0xfb, 0x9b, 0x41, 0x0e, 0x0f, 0xf7, 0x1f, 0x38, 0x26,
	0xad, 0xc8, 0x20, 0x56, 0xc1, 0x5c, 0x63, 0x59, 0xc5, 0x36, 0xd8, 0x7b, 0xdb, 0x50, 0xd9, 0x6c,
	0xc3, 0x76, 0x93, 0xaa, 0xc6, 0x26, 0x6d, 0xf6, 0xae, 0x56, 0xde, 0x3b, 0x06, 0xb5, 0x47, 0x19,
	0x7e, 0x14, 0xbb, 0x83, 0x36, 0xbf, 0xc0, 0x87, 0xd5, 0xee, 0xc3, 0x93, 0xd2, 0xf4, 0xd1, 0xe6,
	0x27, 0x59, 0x7e, 0x73, 0x29, 0x02, 0x2d, 0xa6, 0x98, 0x35, 0xbf, 0x83, 0x1f, 0x48, 0x0f, 0xa5,
	0xd8, 0xe1, 0x02, 0xf1, 0x64, 0x29, 0xc3, 0x8f, 0x57, 0xb1, 0xce, 0xd3, 0x2f, 0x5c, 0xde, 0x83,
	0x2e, 0x52, 0x47, 0x41, 0x9a, 0xab, 0x30, 0x53, 0x2c, 0xbf, 0x81, 0x1f, 0x89, 0x7f, 0xf7, 0x00,
	0xe7, 0x1d, 0x05, 0xe9, 0x03, 0x39, 0x79, 0xb3, 0xb7, 0x01, 0xfe, 0x0b, 0xa6, 0xf5, 0x4e, 0xe9,
	0xa0, 0x9e, 0xf1, 0x15, 0xac, 0x08, 0x7f, 0x8b, 0x8a, 0xd0, 0xce, 0x84, 0xaf, 0x96, 0x7b, 0x40,
	0xf4, 0x0b, 0x20, 0xda, 0xd7, 0xff, 0xd6, 0xa1, 0x39, 0x96, 0x42, 0x68, 0x21, 0xd9, 0x5f, 0xd0,
	0x19, 0x0b, 0x4d, 0x3a, 0x1e, 0xad, 0x1f, 0x56, 0x11, 0x3b, 0xdd, 0xe8, 0xe2, 0x93, 0xa5, 0x73,
	0xbf, 0x94, 0x4e, 0x8b, 0xcd, 0xe1, 0x16, 0xbb, 0x85, 0xa3, 0x2d, 0x0b, 0x09, 0xd2, 0xfd, 0x9c,
	0x06, 0x17, 0xef, 0x10, 0xc9, 0x9f, 0x00, 0x48, 0x92, 0x7f, 0x0d, 0xba, 0x26, 0x41, 0x16, 0x75,
	0xcb, 0xd1, 0xcd, 0x97, 0x83, 0x5b, 0xec, 0x0f, 0xf8, 0x7e, 0x2c, 0xb4, 0x9f, 0xaa, 0xd1, 0x7a,
	0x88, 0x63, 0x3b, 0x36, 0x6e, 0xeb, 0xd4, 0xbc, 0x58, 0x6c, 0x04, 0xb7, 0xd8, 0x0d, 0xb4, 0xe9,
	0x62, 0x9e, 0xf6, 0x4f, 0x3b, 0xf7, 0x36, 0x39, 0x97, 0xd7, 0x85, 0x5b, 0x6c, 0x0c, 0xc7, 0x4f,
	0x22, 0x7e, 0xf6, 0x4b, 0x22, 0x73, 0xcc, 0xab, 0xdb, 0x13, 0xd7, 0x31, 0x92, 0x2e, 0x9d, 0x70,
	0x8b, 0x0d, 0xe1, 0x64, 0x2c, 0xf4, 0x30, 0xd3, 0x14, 0x89, 0x7a, 0xa8, 0x19, 0x33, 0xa8, 0x68,
	0xd3, 0xdc, 0xde, 0x5e, 0x01, 0xd9, 0x3a, 0x62, 0xf3, 0xe1, 0x96, 0x14, 0x4b, 0x95, 0x9b, 0x69,
	0x94, 0xa4, 0xec, 0x7e, 0x35, 0xdb, 0x5e, 0x56, 0xbe, 0xc5, 0x7c, 0xca, 0xe3, 0x3e, 0x48, 0x69,
	0x88, 0x99, 0xf2, 0xd8, 0x99, 0xc1, 0xb5, 0x2b, 0x5b, 0xf7, 0x67, 0x93, 0x70, 0x4f, 0xef, 0x16,
	0x9b, 0x90, 0xba, 0x30, 0xaf, 0xd1, 0x1a, 0x97, 0x93, 0x7d, 0x35, 0x18, 0xcb, 0x4a, 0x75, 0x5d,
	0x93, 0xad, 0x7c, 0xc6, 0xad, 0x59, 0x83, 0xfe, 0x8e, 0x7f, 0xff, 0x16, 0x00, 0x00, 0xff, 0xff,
	0xf0, 0x90, 0x72, 0xc4, 0x9f, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	GetBlockByNum(ctx context.Context, in *ReqBlockByNumber, opts ...grpc.CallOption) (*RespBlock, error)
	GetBlockByHash(ctx context.Context, in *ReqBlockByHash, opts ...grpc.CallOption) (*RespBlock, error)
	GetBalance(ctx context.Context, in *ReqBalance, opts ...grpc.CallOption) (*ResBalance, error)
	GetTxsByAddr(ctx context.Context, in *ReqTx, opts ...grpc.CallOption) (*ResposeTxs, error)
	GetTxByHash(ctx context.Context, in *ReqTxByHash, opts ...grpc.CallOption) (*Tx, error)
	SendTransaction(ctx context.Context, in *ReqTransaction, opts ...grpc.CallOption) (*ResTransaction, error)
	GetAddressNonceAt(ctx context.Context, in *ReqNonce, opts ...grpc.CallOption) (*ResposeNonce, error)
	CreateAddr(ctx context.Context, in *ReqCreateAddr, opts ...grpc.CallOption) (*RespCreateAddr, error)
	GetMaxBlockNumber(ctx context.Context, in *ReqMaxBlockNumber, opts ...grpc.CallOption) (*RespMaxBlockNumber, error)
	GetAddrByPriv(ctx context.Context, in *ReqAddrByPriv, opts ...grpc.CallOption) (*RespAddrByPriv, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetBlockByNum(ctx context.Context, in *ReqBlockByNumber, opts ...grpc.CallOption) (*RespBlock, error) {
	out := new(RespBlock)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBlockByNum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetBlockByHash(ctx context.Context, in *ReqBlockByHash, opts ...grpc.CallOption) (*RespBlock, error) {
	out := new(RespBlock)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBlockByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetBalance(ctx context.Context, in *ReqBalance, opts ...grpc.CallOption) (*ResBalance, error) {
	out := new(ResBalance)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetTxsByAddr(ctx context.Context, in *ReqTx, opts ...grpc.CallOption) (*ResposeTxs, error) {
	out := new(ResposeTxs)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetTxsByAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetTxByHash(ctx context.Context, in *ReqTxByHash, opts ...grpc.CallOption) (*Tx, error) {
	out := new(Tx)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetTxByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SendTransaction(ctx context.Context, in *ReqTransaction, opts ...grpc.CallOption) (*ResTransaction, error) {
	out := new(ResTransaction)
	err := c.cc.Invoke(ctx, "/message.Greeter/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetAddressNonceAt(ctx context.Context, in *ReqNonce, opts ...grpc.CallOption) (*ResposeNonce, error) {
	out := new(ResposeNonce)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetAddressNonceAt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) CreateAddr(ctx context.Context, in *ReqCreateAddr, opts ...grpc.CallOption) (*RespCreateAddr, error) {
	out := new(RespCreateAddr)
	err := c.cc.Invoke(ctx, "/message.Greeter/CreateAddr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetMaxBlockNumber(ctx context.Context, in *ReqMaxBlockNumber, opts ...grpc.CallOption) (*RespMaxBlockNumber, error) {
	out := new(RespMaxBlockNumber)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetMaxBlockNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) GetAddrByPriv(ctx context.Context, in *ReqAddrByPriv, opts ...grpc.CallOption) (*RespAddrByPriv, error) {
	out := new(RespAddrByPriv)
	err := c.cc.Invoke(ctx, "/message.Greeter/GetAddrByPriv", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	GetBlockByNum(context.Context, *ReqBlockByNumber) (*RespBlock, error)
	GetBlockByHash(context.Context, *ReqBlockByHash) (*RespBlock, error)
	GetBalance(context.Context, *ReqBalance) (*ResBalance, error)
	GetTxsByAddr(context.Context, *ReqTx) (*ResposeTxs, error)
	GetTxByHash(context.Context, *ReqTxByHash) (*Tx, error)
	SendTransaction(context.Context, *ReqTransaction) (*ResTransaction, error)
	GetAddressNonceAt(context.Context, *ReqNonce) (*ResposeNonce, error)
	CreateAddr(context.Context, *ReqCreateAddr) (*RespCreateAddr, error)
	GetMaxBlockNumber(context.Context, *ReqMaxBlockNumber) (*RespMaxBlockNumber, error)
	GetAddrByPriv(context.Context, *ReqAddrByPriv) (*RespAddrByPriv, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GetBlockByNum(ctx context.Context, req *ReqBlockByNumber) (*RespBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByNum not implemented")
}
func (*UnimplementedGreeterServer) GetBlockByHash(ctx context.Context, req *ReqBlockByHash) (*RespBlock, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByHash not implemented")
}
func (*UnimplementedGreeterServer) GetBalance(ctx context.Context, req *ReqBalance) (*ResBalance, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (*UnimplementedGreeterServer) GetTxsByAddr(ctx context.Context, req *ReqTx) (*ResposeTxs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxsByAddr not implemented")
}
func (*UnimplementedGreeterServer) GetTxByHash(ctx context.Context, req *ReqTxByHash) (*Tx, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxByHash not implemented")
}
func (*UnimplementedGreeterServer) SendTransaction(ctx context.Context, req *ReqTransaction) (*ResTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (*UnimplementedGreeterServer) GetAddressNonceAt(ctx context.Context, req *ReqNonce) (*ResposeNonce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressNonceAt not implemented")
}
func (*UnimplementedGreeterServer) CreateAddr(ctx context.Context, req *ReqCreateAddr) (*RespCreateAddr, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAddr not implemented")
}
func (*UnimplementedGreeterServer) GetMaxBlockNumber(ctx context.Context, req *ReqMaxBlockNumber) (*RespMaxBlockNumber, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMaxBlockNumber not implemented")
}
func (*UnimplementedGreeterServer) GetAddrByPriv(ctx context.Context, req *ReqAddrByPriv) (*RespAddrByPriv, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddrByPriv not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetBlockByNum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBlockByNum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBlockByNum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBlockByNum(ctx, req.(*ReqBlockByNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetBlockByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBlockByHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBlockByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBlockByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBlockByHash(ctx, req.(*ReqBlockByHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqBalance)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBalance(ctx, req.(*ReqBalance))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetTxsByAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetTxsByAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetTxsByAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetTxsByAddr(ctx, req.(*ReqTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetTxByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTxByHash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetTxByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetTxByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetTxByHash(ctx, req.(*ReqTxByHash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SendTransaction(ctx, req.(*ReqTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetAddressNonceAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqNonce)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetAddressNonceAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetAddressNonceAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetAddressNonceAt(ctx, req.(*ReqNonce))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_CreateAddr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCreateAddr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).CreateAddr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/CreateAddr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).CreateAddr(ctx, req.(*ReqCreateAddr))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetMaxBlockNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqMaxBlockNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetMaxBlockNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetMaxBlockNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetMaxBlockNumber(ctx, req.(*ReqMaxBlockNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_GetAddrByPriv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqAddrByPriv)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetAddrByPriv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Greeter/GetAddrByPriv",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetAddrByPriv(ctx, req.(*ReqAddrByPriv))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockByNum",
			Handler:    _Greeter_GetBlockByNum_Handler,
		},
		{
			MethodName: "GetBlockByHash",
			Handler:    _Greeter_GetBlockByHash_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _Greeter_GetBalance_Handler,
		},
		{
			MethodName: "GetTxsByAddr",
			Handler:    _Greeter_GetTxsByAddr_Handler,
		},
		{
			MethodName: "GetTxByHash",
			Handler:    _Greeter_GetTxByHash_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _Greeter_SendTransaction_Handler,
		},
		{
			MethodName: "GetAddressNonceAt",
			Handler:    _Greeter_GetAddressNonceAt_Handler,
		},
		{
			MethodName: "CreateAddr",
			Handler:    _Greeter_CreateAddr_Handler,
		},
		{
			MethodName: "GetMaxBlockNumber",
			Handler:    _Greeter_GetMaxBlockNumber_Handler,
		},
		{
			MethodName: "GetAddrByPriv",
			Handler:    _Greeter_GetAddrByPriv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
